# Generated by Django 4.2.4 on 2023-08-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='created',
            new_name='created_at',
        ),
    ]
