# Generated by Django 4.2.4 on 2023-08-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0003_alter_password_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
